const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';
const IS_LOGGED_IN = 'IS_LOGGED_IN';

export const loginTypes = {
    FETCH_LOGIN_REQUEST,
    FETCH_LOGIN_SUCCESS,
    FETCH_LOGIN_FAILURE,
    IS_LOGGED_IN
};