const FETCH_PET_ADD_RESET = 'FETCH_PET_ADD_RESET';
const FETCH_PET_ADD_REQUEST = 'FETCH_PET_ADD_REQUEST';
const FETCH_PET_ADD_SUCCESS = 'FETCH_PET_ADD_SUCCESS';
const FETCH_PET_ADD_FAILURE = 'FETCH_PET_ADD_FAILURE';
const FETCH_PET_GET_LIST_REQUEST = 'FETCH_PET_GET_LIST_REQUEST';
const FETCH_PET_GET_LIST_SUCCESS = 'FETCH_PET_GET_LIST_SUCCESS';
const FETCH_PET_GET_LIST_FAILURE = 'FETCH_PET_GET_LIST_FAILURE';
const FETCH_PET_GET_ONE_REQUEST = 'FETCH_PET_GET_ONE_REQUEST';
const FETCH_PET_GET_ONE_SUCCESS = 'FETCH_PET_GET_ONE_SUCCESS';
const FETCH_PET_GET_ONE_FAILURE = 'FETCH_PET_GET_ONE_FAILURE';
const FETCH_PET_UPDATE_RESET = 'FETCH_PET_UPDATE_RESET';
const FETCH_PET_UPDATE_REQUEST = 'FETCH_PET_UPDATE_REQUEST';
const FETCH_PET_UPDATE_SUCCESS = 'FETCH_PET_UPDATE_SUCCESS';
const FETCH_PET_UPDATE_FAILURE = 'FETCH_PET_UPDATE_FAILURE';

export const petTypes = {
    FETCH_PET_ADD_RESET,
    FETCH_PET_ADD_REQUEST,
    FETCH_PET_ADD_SUCCESS,
    FETCH_PET_ADD_FAILURE,
    FETCH_PET_GET_LIST_REQUEST,
    FETCH_PET_GET_LIST_SUCCESS,
    FETCH_PET_GET_LIST_FAILURE,
    FETCH_PET_GET_ONE_REQUEST,
    FETCH_PET_GET_ONE_SUCCESS,
    FETCH_PET_GET_ONE_FAILURE,
    FETCH_PET_UPDATE_RESET,
    FETCH_PET_UPDATE_REQUEST,
    FETCH_PET_UPDATE_SUCCESS,
    FETCH_PET_UPDATE_FAILURE
};