const FETCH_PET_ADD_RESET = 'FETCH_PET_ADD_RESET';
const FETCH_PET_ADD_REQUEST = 'FETCH_PET_ADD_REQUEST';
const FETCH_PET_ADD_SUCCESS = 'FETCH_PET_ADD_SUCCESS';
const FETCH_PET_ADD_FAILURE = 'FETCH_PET_ADD_FAILURE';
const FETCH_PET_GET_LIST_REQUEST = 'FETCH_PET_GET_LIST_REQUEST';
const FETCH_PET_GET_LIST_SUCCESS = 'FETCH_PET_GET_LIST_SUCCESS';
const FETCH_PET_GET_LIST_FAILURE = 'FETCH_PET_GET_LIST_FAILURE';

export const petTypes = {
    FETCH_PET_ADD_RESET,
    FETCH_PET_ADD_REQUEST,
    FETCH_PET_ADD_SUCCESS,
    FETCH_PET_ADD_FAILURE,
    FETCH_PET_GET_LIST_REQUEST,
    FETCH_PET_GET_LIST_SUCCESS,
    FETCH_PET_GET_LIST_FAILURE
};