const FETCH_CARE_ADD_RESET = 'FETCH_CARE_ADD_RESET';
const FETCH_CARE_ADD_REQUEST = 'FETCH_CARE_ADD_REQUEST';
const FETCH_CARE_ADD_SUCCESS = 'FETCH_CARE_ADD_SUCCESS';
const FETCH_CARE_ADD_FAILURE = 'FETCH_CARE_ADD_FAILURE';
const FETCH_CARE_GET_LIST_REQUEST = 'FETCH_CARE_GET_LIST_REQUEST';
const FETCH_CARE_GET_LIST_SUCCESS = 'FETCH_CARE_GET_LIST_SUCCESS';
const FETCH_CARE_GET_LIST_FAILURE = 'FETCH_CARE_GET_LIST_FAILURE';
const FETCH_CARE_GET_ONE_REQUEST = 'FETCH_CARE_GET_ONE_REQUEST';
const FETCH_CARE_GET_ONE_SUCCESS = 'FETCH_CARE_GET_ONE_SUCCESS';
const FETCH_CARE_GET_ONE_FAILURE = 'FETCH_CARE_GET_ONE_FAILURE';
const FETCH_CARE_UPDATE_RESET = 'FETCH_CARE_UPDATE_RESET';
const FETCH_CARE_UPDATE_REQUEST = 'FETCH_CARE_UPDATE_REQUEST';
const FETCH_CARE_UPDATE_SUCCESS = 'FETCH_CARE_UPDATE_SUCCESS';
const FETCH_CARE_UPDATE_FAILURE = 'FETCH_CARE_UPDATE_FAILURE';

export const careTypes = {
    FETCH_CARE_ADD_RESET,
    FETCH_CARE_ADD_REQUEST,
    FETCH_CARE_ADD_SUCCESS,
    FETCH_CARE_ADD_FAILURE,
    FETCH_CARE_GET_LIST_REQUEST,
    FETCH_CARE_GET_LIST_SUCCESS,
    FETCH_CARE_GET_LIST_FAILURE,
    FETCH_CARE_GET_ONE_REQUEST,
    FETCH_CARE_GET_ONE_SUCCESS,
    FETCH_CARE_GET_ONE_FAILURE,
    FETCH_CARE_UPDATE_RESET,
    FETCH_CARE_UPDATE_REQUEST,
    FETCH_CARE_UPDATE_SUCCESS,
    FETCH_CARE_UPDATE_FAILURE
};