const FETCH_PASSWORD_RESET = 'FETCH_PASSWORD_RESET';
const FETCH_PASSWORD_RESET_SUCCESS = 'FETCH_PASSWORD_RESET_SUCCESS';
const FETCH_PASSWORD_RESET_FAILURE = 'FETCH_PASSWORD_RESET_FAILURE';
const FETCH_PASSWORD_CHANGE = 'FETCH_PASSWORD_CHANGE';
const FETCH_PASSWORD_CHANGE_SUCCESS = 'FETCH_PASSWORD_CHANGE_SUCCESS';
const FETCH_PASSWORD_CHANGE_FAILURE = 'FETCH_PASSWORD_CHANGE_FAILURE';

export const passwordTypes = {
    FETCH_PASSWORD_RESET,
    FETCH_PASSWORD_RESET_SUCCESS,
    FETCH_PASSWORD_RESET_FAILURE,
    FETCH_PASSWORD_CHANGE,
    FETCH_PASSWORD_CHANGE_SUCCESS,
    FETCH_PASSWORD_CHANGE_FAILURE
};