const FETCH_SIGNUP_REQUEST = 'FETCH_SIGNUP_REQUEST';
const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS';
const FETCH_SIGNUP_FAILURE = 'FETCH_SIGNUP_FAILURE';

export const signupTypes = {
    FETCH_SIGNUP_REQUEST,
    FETCH_SIGNUP_SUCCESS,
    FETCH_SIGNUP_FAILURE
};